Add support for mio v0.8
vorner/signal-hook pull request #131
Opened 2022-03-14 14:02 UTC by pickfire

Add support for mio-v0.8, not sure if this is the best way since it duplicates most of the v0.7, also not sure if there is a better way for this doing this, this allows helix which in terms depends on crossterm to be able to use signal-hook-mio with v0.8 to prevent crate duplication.

2022-03-15 08:24 UTC, vorner commented
Hello

I've somewhat busy time right now, I'll get around to it in a week or two. In general, having the support is welcome, I'll have a look at the details if this is the best way. I think some support for something already had a lot of duplication and was solving it by macros.

2022-03-19 15:34 UTC, vorner requested changes
Can you have a look at the tests?

2022-03-19 15:34 UTC, vorner commented on signal-hook-mio/tests/mio_0_7.rs
> +#![cfg(any(feature = "support-v0_7", feature = "support-v0_8"))]
I think this'll not test both features if both are enabled. Can you create a separate one for mio 0.8? Can you also check that there's a CI setup with mio 0.8 enabled (there might be some with `--all-features` or some such).

2022-03-27 07:27 UTC, merged

2022-03-27 08:08 UTC, vorner commented
Thank you, released

2022-03-27 11:56 UTC, pickfire commented
I think you forgot to upload it to https://crates.io/crates/signal-hook-mio

2022-03-27 12:07 UTC, vorner commented
You're right. Fixed now.