Support AIX signal handler types
vorner/signal-hook pull request #136
Opened 2022-09-28 09:33 UTC by ecnelises

The main differences for AIX:
- AIX doesn't have `MSG_DONTWAIT`, instead, use `MSG_NONBLOCK` (https://github.com/stephane/libmodbus/issues/294)
- AIX definition for sigaction handler is different: `sa_union { __su_handler: extern fn(c: ::c_int), __su_sigaction: extern fn(c: ::c_int, info: *mut siginfo_t, ptr: *mut ::c_void) }`

Note that AIX hasn't been an official Tier-3 Rust target. (https://github.com/rust-lang/compiler-team/issues/553)

2022-10-02 12:08 UTC, vorner requested changes
Hello

There are some style issues that would be nice to get addressed. Nevertheless, there's this bigger concern I have.

You mention that AIX is not yet a tier-3 Rust target. When trying to look at the libc crate, it doesn't seem to offer any aix target officially and grepping it for the word `aix` yields nothing, so is it even supported by libc? Or is it some kind of unofficial fork of the libc crate?

So I'd like to know how stable that target is, if it's likely to change (like, if the `libc` crate might paper-over the differences in the names, for example, in the future, which would break the currently proposed code). If it's not going to change, having it included in the CI in some way would be nice, because I have no other way to tell if it has any chance to work or if some future changes would break it.

2022-10-09 05:50 UTC, ecnelises commented
> You mention that AIX is not yet a tier-3 Rust target. When trying to look at the libc crate, it doesn't seem to offer any aix target officially and grepping it for the word aix yields nothing, so is it even supported by libc? Or is it some kind of unofficial fork of the libc crate?
>
> So I'd like to know how stable that target is, if it's likely to change (like, if the libc crate might paper-over the differences in the names, for example, in the future, which would break the currently proposed code). If it's not going to change, having it included in the CI in some way would be nice, because I have no other way to tell if it has any chance to work or if some future changes would break it.

AIX has not been an official Rust target yet. We have a proposal here https://github.com/rust-lang/compiler-team/issues/553 and multiple patches like https://github.com/rust-lang/libc/pull/2894. So this PR might need to be in draft status.

As for CI, we also plan to gradually set up CI for Rust toolchain after AIX target got accepted, but since it seems no public CI system supports AIX, we need to figure out how to support CI of these critical crates (also FYI @bzeq). Is that the necessity for now?

2022-10-21 18:55 UTC, vorner commented
> As for CI, we also plan to gradually set up CI for Rust toolchain after AIX target got accepted, but since it seems no public CI system supports AIX, we need to figure out how to support CI of these critical crates (also FYI @bzEq). Is that the necessity for now?

Not necessarily. Considering the state of the proposal, etc, I'd be OK merging it with the knowledge this is an experimental target, not guaranteed to work or compile despite the crate being past 1.0. That is, I'm OK accepting it and even publishing a new version if it helps you, but until there's some CI and such, I can't promise not to accidentally break it in some future version :shrug:. If that's fine for you, we can go forward with this.

2023-02-01 07:00 UTC, ecnelises commented
> Not necessarily. Considering the state of the proposal, etc, I'd be OK merging it with the knowledge this is an experimental target, not guaranteed to work or compile despite the crate being past 1.0. That is, I'm OK accepting it and even publishing a new version if it helps you, but until there's some CI and such, I can't promise not to accidentally break it in some future version 🤷. If that's fine for you, we can go forward with this.

Thanks. Now `powerpc64-ibm-aix` has been accepted as Tier-3 target. I'm okay with potential build break from future change due to lack of CI.

2023-02-11 13:04 UTC, vorner approved these changes

2023-02-11 13:04 UTC, merged

2023-02-11 14:21 UTC, vorner commented
Thank you, released…

2023-02-13 02:20 UTC, ecnelises commented
Thanks!